import { FriendTypeEnum } from 'app/enums/friendEnum';
export interface FriendParams {
  fid: number;
}

export interface GetFriendParams {
  page?: number;
  type: FriendTypeEnum;
  search?: string;
  limit?: number;
}
// Generated by https://quicktype.io

export interface Friend {
  id: number;
  idRequest: number;
  name: string;
  avatar: string;
}
