// Generated by https://quicktype.io

export interface CropMedia {
  creationDate: string;
  cropRect: any;
  data: any;
  duration: any;
  exif: any;
  filename: string;
  height: number;
  localIdentifier: string;
  mime: string;
  modificationDate: string;
  path: string;
  size: number;
  sourceURL: string;
  width: number;
  thumbnail?: string;
}
