export interface Media {
  id: number;
  coverImage: string;
  type: number;
  totalLike: number;
  totalComment: number;
  totalShare: number;
  totalCupon: number;
  isLiked: boolean;
  createdAt: string;
  uri?: string;
}
export interface Customer {
  id: number;
  name: string;
  avatar: string;
  type?: number;
}

export interface Shared {
  customer: {
    id: number;
    name: string;
    avatar: string;
    type: number;
    totalLike: number;
    isLiked: boolean;
  };
  id: number;
  createdAt: string;
  sortContent: string;
  content: string;
  totalLike: number;
  totalComment: number;
  totalShare: number;
  isLiked: boolean;
  length: number;
  role: number;
  type: number;
}

export interface TagFriend {
  name: string;
  id: number;
}

export interface Tour {
  id: number;
  discount: any;
  image: string;
  name: string;
  price: number;
  startTime: string;
  desc: string;
  schedule: any;
}

export type Post = {
  id: number;
  shareType?: string;
  customer: Customer;
  tour: Tour;
  tag_friends?: TagFriend[];
  sortContent: string;
  content: string;
  title: string;
  media: Media[];
  image_experience: string;
  type: 1 | 2 | 3 | 4;
  role: number;
  totalLike: number;
  totalComment: number;
  totalShare: number;
  totalCupon: number;
  isLiked: boolean;
  createdAt: string;
  shareBy: Shared;
};

export interface Explore {
  id: number;
  shareType?: string;
  customer: Customer;
  tour: Tour;
  tag_friends?: TagFriend[];
  sortContent: string;
  content: string;
  title: string;
  media: Media[];
  image_experience: string;
  type: 1 | 2 | 3 | 4;
  role: number;
  totalLike: number;
  totalComment: number;
  totalShare: number;
  totalCupon: number;
  isLiked: boolean;
  createdAt: string;
  shareBy: Shared;
}

export interface PostParams {
  page: number;
  type?: number;
}

export interface CreatePostParams {
  content?: string;
  role?: string;
  share_type: string;
  tag_friends?: string;
  image?: any;
  share_id?: number;
}

export enum TargetTypeEnum {
  Post = 'post',
  Tour = 'tour',
  Experience = 'experience',
  Comment = 'comment',
}
export interface LikeParams {
  id: number;
  target_type: string;
}

// Generated by https://quicktype.io

export interface PostFriend {
  id: number;
  name: string;
  avatar: string;
  status: number;
}
export interface GetPostFriendParams {
  search: string;
  page?: number;
}
