// Generated by https://quicktype.io

export interface TourOrder {
  id: number;
  tourName: string;
  customerName: string;
  phone: string;
  address: string;
  startTime: string;
  endTime: string;
  startPlace: string;
  numberDay: number;
  member: string;
  totalSpend: number;
  paymentStatus: number;
  discountPrice: number;
  coverImage: string;
  createdAt: string;
  orderId: string;
  status: number;
}
// Generated by https://quicktype.io

export interface Order {
  id: number;
  tourName: string;
  startTime: string;
  endTime: string;
  numberDay: number;
  member: string;
  totalPrice: number;
  status: number;
  coverImage: string;
}
export interface GetOrderParams {
  page?: number;
  status?: number;
}

// Generated by https://quicktype.io

export interface TourDetail {
  id: number;
  image: string;
  name: string;
  price: number;
  priceAfterDiscount: number;
  discount: any;
  desc: string;
  startTime: string;
  schedule: string;
  endTime: string;
  totalLike: number;
  totalComment: number;
  totalShare: number;
  summary: string;
  vehicle: string;
  hotel: null;
  totalDay: number;
  totalNight: null;
  startPlace: string;
  finishPlace: string;
  tourCode: string;
  schedulePlan: any[];
  priceDetail: any[];
  isLiked: boolean;
}

// Generated by https://quicktype.io

export interface City {
  id: number;
  name: string;
  country: Country;
}

export interface Country {
  id: number;
  name: string;
}

export interface GetCityParams {
  page?: number;
  search_name?: string;
}
